# -*- coding: utf-8 -*-
"""rl_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_aNvyKo-fAIyvytejUWXsfLxY281QtF
"""

import streamlit as st
import gymnasium as gym
from gymnasium import spaces
import numpy as np
import pandas as pd
import yfinance as yf
import ta
import matplotlib.pyplot as plt

from stable_baselines3 import PPO


# ============================================================
# CONFIGURACIÓN
# ============================================================

st.set_page_config(
    page_title="Nopal Quant - Reinforcement Learning",
    page_icon="📈",
    layout="wide"
)

st.title("Nopal Quant")
st.subheader("Reinforcement Learning Trading Agent")

st.write(
    "El agente PPO aprende una estrategia de trading utilizando "
    "rendimientos, RSI y media móvil."
)


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.header("Parámetros")

ticker = st.sidebar.text_input(
    "Clave Yahoo Finance",
    value="BIMBOA.MX"
).upper().strip()

periodo = st.sidebar.selectbox(
    "Periodo histórico",
    ["6mo", "1y", "2y", "5y", "10y"],
    index=2
)

window = st.sidebar.slider(
    "Ventana de observaciones",
    min_value=5,
    max_value=30,
    value=10
)

cost = st.sidebar.number_input(
    "Costo de transacción",
    min_value=0.0,
    max_value=0.02,
    value=0.0025,
    step=0.0001,
    format="%.4f"
)

timesteps = st.sidebar.selectbox(
    "Pasos de entrenamiento PPO",
    [10_000, 25_000, 50_000, 100_000],
    index=3
)

ejecutar = st.sidebar.button(
    "🚀 Entrenar agente",
    type="primary"
)


# ============================================================
# ENTORNO DE TRADING
# ============================================================

class TradingEnv(gym.Env):

    def __init__(self, df, window=10, cost=0.001):

        super().__init__()

        self.df = df.reset_index(drop=True)
        self.window = window
        self.cost = cost

        # 0 = mantener
        # 1 = comprar
        # 2 = vender
        self.action_space = spaces.Discrete(3)

        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(window + 2,),
            dtype=np.float32
        )

        self.reset()

    def reset(self, seed=None, options=None):

        super().reset(seed=seed)

        self.t = self.window
        self.position = 0

        return self._get_obs(), {}

    def _get_obs(self):

        returns = self.df["Return"].iloc[
            self.t - self.window:self.t
        ].values

        rsi = self.df["RSI"].iloc[self.t]

        ma = self.df["MA"].iloc[self.t]

        return np.concatenate(
            [returns, [rsi, ma]]
        ).astype(np.float32)

    def step(self, action):

        prev_position = self.position

        # ----------------------------
        # Decisión del agente
        # ----------------------------

        if action == 1:
            self.position = 1

        elif action == 2:
            self.position = 0

        # ----------------------------
        # Rendimiento
        # ----------------------------

        ret = self.df["Return"].iloc[self.t]

        reward = self.position * ret

        # ----------------------------
        # Costo de transacción
        # ----------------------------

        reward -= self.cost * abs(
            self.position - prev_position
        )

        # ----------------------------
        # Avanzar en el tiempo
        # ----------------------------

        self.t += 1

        terminated = self.t >= len(self.df) - 1

        truncated = False

        return (
            self._get_obs(),
            float(reward),
            terminated,
            truncated,
            {}
        )


# ============================================================
# DESCARGAR DATOS
# ============================================================

@st.cache_data
def descargar_datos(ticker, periodo):

    df = yf.download(
        ticker,
        period=periodo,
        auto_adjust=True,
        progress=False
    )

    if df.empty:
        return None

    # Manejar MultiIndex de Yahoo Finance
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    df["Close"] = df["Close"].squeeze()
    df["Volume"] = df["Volume"].squeeze()

    # ----------------------------
    # Variables financieras
    # ----------------------------

    df["Return"] = df["Close"].pct_change()

    df["RSI"] = ta.momentum.RSIIndicator(
        close=df["Close"],
        window=14
    ).rsi()

    df["MA"] = df["Close"].rolling(20).mean()

    df = df.dropna()

    return df


# ============================================================
# MOSTRAR DATOS
# ============================================================

df = descargar_datos(ticker, periodo)

if df is None:

    st.error(
        f"No se encontraron datos para **{ticker}**."
    )

    st.stop()


st.success(
    f"Datos descargados correctamente: {ticker}"
)


# ============================================================
# INFORMACIÓN DEL ACTIVO
# ============================================================

col1, col2, col3, col4 = st.columns(4)

col1.metric(
    "Precio actual",
    f"${df['Close'].iloc[-1]:,.2f}"
)

col2.metric(
    "Observaciones",
    f"{len(df):,}"
)

col3.metric(
    "RSI",
    f"{df['RSI'].iloc[-1]:.2f}"
)

col4.metric(
    "Media móvil 20",
    f"${df['MA'].iloc[-1]:,.2f}"
)


# ============================================================
# GRÁFICA DEL PRECIO
# ============================================================

st.subheader("Precio y media móvil")

fig, ax = plt.subplots()

ax.plot(
    df.index,
    df["Close"],
    label="Close"
)

ax.plot(
    df.index,
    df["MA"],
    label="MA(20)"
)

ax.set_title(f"{ticker} - Precio")
ax.legend()

st.pyplot(fig)


# ============================================================
# ENTRENAMIENTO
# ============================================================

if ejecutar:

    st.subheader("Entrenamiento del agente PPO")

    with st.spinner(
        "Entrenando agente de Reinforcement Learning..."
    ):

        env = TradingEnv(
            df,
            window=window,
            cost=cost
        )

        model = PPO(
            "MlpPolicy",
            env,
            verbose=0
        )

        model.learn(
            total_timesteps=timesteps
        )

    st.success(
        f"Entrenamiento terminado: "
        f"{timesteps:,} pasos"
    )


    # ========================================================
    # SIMULACIÓN
    # ========================================================

    obs, _ = env.reset()

    terminated = False
    truncated = False

    capital = 1.0

    capital_history = [capital]

    actions = []

    positions = []

    while not (terminated or truncated):

        action, _ = model.predict(
            obs,
            deterministic=True
        )

        action = int(action)

        actions.append(action)

        obs, reward, terminated, truncated, _ = env.step(
            action
        )

        capital *= (1 + reward)

        capital_history.append(capital)

        positions.append(env.position)


    # ========================================================
    # RESULTADOS
    # ========================================================

    st.subheader("Resultado de la estrategia")

    retorno = capital - 1

    buy_hold = (
        df["Close"].iloc[-1]
        /
        df["Close"].iloc[window]
        - 1
    )

    col1, col2, col3 = st.columns(3)

    col1.metric(
        "Capital final",
        f"{capital:.4f}"
    )

    col2.metric(
        "Retorno RL",
        f"{retorno * 100:.2f}%"
    )

    col3.metric(
        "Buy & Hold",
        f"{buy_hold * 100:.2f}%"
    )


    # ========================================================
    # CAPITAL
    # ========================================================

    st.subheader("Evolución del capital")

    fig2, ax2 = plt.subplots()

    ax2.plot(
        capital_history,
        label="PPO Trading Strategy"
    )

    ax2.axhline(
        1,
        linestyle="--",
        label="Capital inicial"
    )

    ax2.set_title(
        f"{ticker} - Capital de la estrategia"
    )

    ax2.set_xlabel("Periodo")
    ax2.set_ylabel("Capital")

    ax2.legend()

    st.pyplot(fig2)


    # ========================================================
    # POSICIÓN
    # ========================================================

    st.subheader("Posición del agente")

    fig3, ax3 = plt.subplots()

    ax3.step(
        range(len(positions)),
        positions,
        where="post"
    )

    ax3.set_title(
        "Decisiones del agente"
    )

    ax3.set_xlabel("Periodo")

    ax3.set_ylabel(
        "Posición: 0 = efectivo, 1 = activo"
    )

    st.pyplot(fig3)


    # ========================================================
    # INTERPRETACIÓN
    # ========================================================

    st.subheader("Interpretación")

    if retorno > buy_hold:

        st.success(
            "El agente PPO obtuvo un rendimiento "
            "superior al enfoque Buy & Hold en esta simulación."
        )

    else:

        st.warning(
            "El agente PPO obtuvo un rendimiento "
            "inferior al enfoque Buy & Hold en esta simulación."
        )

    st.info(
        "Este resultado corresponde a una simulación histórica "
        "y no garantiza rendimientos futuros."
    )
